### PR TITLE
Dev vm_HW_Pull request

### PR DESCRIPTION
**Pull request by VikMoskalenko**

### CODE REVIEW

**Comment by Vadim211** [comment]
Don't forget to pull changes first from master branch to avoid conflicts in code

**Review by Vadim211 — APPROVED** [review]

**Comment by ebriuspythagoras** [comment]
I reviewed

**Review by ebriuspythagoras — COMMENTED** [review]
I reviewed

**Review by ebriuspythagoras — APPROVED** [review]
Good

**Comment by Vadim211** [comment]
Don't forget to update master branch locally to avoid conflicts

**Review by Vadim211 — APPROVED** [review]

**Review by IlliaKrasheninnikov — COMMENTED** [review]
Good work

**Review by IlliaKrasheninnikov — APPROVED** [review]

**Pull request merged**
