### PR TITLE
WriteLine modification

### PR DESCRIPTION
**Pull request by ebriuspythagoras**
Add ---

### CODE REVIEW

**Comment by Vadim211** [comment]
You need to add reviews

**Comment by ebriuspythagoras** [comment]
@Vadim211 done

**Review by IlliaKrasheninnikov — COMMENTED** [review]
Nice

**Review by IlliaKrasheninnikov — APPROVED** [review]

**Review by DanyloNaumenko — APPROVED** [review]
Approved)

**Pull request merged**
